agent_name = "gradient-bang-bot"
image = "your_username/gradient-bang-bot:latest"
secret_set = "gb-bot-secrets"
agent_profile = "agent-1x"

# RECOMMENDED: Set an image pull secret:
# https://docs.pipecat.ai/deployment/pipecat-cloud/fundamentals/secrets#image-pull-secrets
# image_credentials = "your_image_pull_secret"

[krisp_viva]
audio_filter = "tel" 
# audio_filter = "pro" for 32kHz

[scaling]
	min_agents = 1